name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        shell: bash
        run: |
          dotnet tool update dotnet-sonarscanner --global
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet sonarscanner begin /k:"teste-andre" /d:sonar.login="sqp_fa23d8ec93cdb82eb0a30e9a31122a9e11647556" /d:sonar.host.url="https://sonar.gvp-dev.com"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="sqp_fa23d8ec93cdb82eb0a30e9a31122a9e11647556"
